cc_binary(
    name = "sandbox-describe",
    srcs = glob(["**/*.hpp"])+ glob(["**/*.h"])+ glob(["**/*.hh"]) + glob(["**/*.cc"]),
    deps = [
        "@boost//:describe",
        "@boost//:json"
    ],
)
